version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wiki_search
    tty: true
    ports:
      - "8080:8080"
  mongo:
    image: mongo
    container_name: mongo
    tty: true
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/date/db



