version: '3'

services:
#  nginx:
#    image: nginx
#    container_name: nginx
#    ports:
#      - "8080:80"
#    volumes:
#      - ./:var/www
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - app
#      - mongo

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wiki_search
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    tty: true
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: wiki_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass



